Repository PyCQA/docformatter, pull requests merged in 2022-08, with the labels that each got.

#53 Removed the empty line between function definiton and docstring #51
  docformatter.py
  test_docformatter.py
Labels: enhancement

#46 Pre-Summary Space Option
  docformatter.py
  test_docformatter.py
Labels: enhancement

#99 fix: definitions corrupted with in-line comment
  docformatter.py
  test_docformatter.py
Labels: bug

#104 feat: add option to place closing quotes on newline
  README.rst
  docformatter.py
  pyproject.toml
  tests/test_format_docstring.py
Labels: P: enhancement, C: convention, V: minor

#105 feat: adjust for tab when wrapping
  README.rst
  docformatter.py
  docs/images/pycharm-file-watcher-configurations.png
  tests/test_format_docstring.py
Labels: P: bug, C: style

#108 chore: add workflow actions
  .github/workflows/ci.yml
  .github/workflows/on-issue-open.yml
  .github/workflows/on-push-tag.yml
  pyproject.toml
Labels: chore

#107 Release v1.5.0
  .github/workflows/do-update-authors.yml
  .github/workflows/on-push-tag.yml
  AUTHORS.rst
  README.rst
  docformatter.py
  docs/Makefile
  docs/make.bat
  docs/source/authors.rst
  docs/source/conf.py
  docs/source/configuration.rst
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/license.rst
  docs/source/requirements.rst
  docs/source/usage.rst
  pyproject.toml
Labels: V: minor, release

#115 fix: don't wrap URLs
  .github/workflows/ci.yml
  .gitignore
  docformatter.py
  docs/source/configuration.rst
  docs/source/requirements.rst
  pyproject.toml
  tests/test_configuration_functions.py
  tests/test_format_docstring.py
Labels: P: bug, C: style, V: patch

#116 feat: format class attribute docstrings
  .github/workflows/ci.yml
  docformatter.py
  pyproject.toml
  tests/test_format_code.py
  tests/test_format_docstring.py
  tests/test_string_functions.py
Labels: P: enhancement, C: convention

#117 chore: move script to src layout and make a package
  .github/workflows/ci.yml
  .github/workflows/do-lint.yml
  MANIFEST.in
  Makefile
  docformatter.py
  pyproject.toml
  setup.py
  src/docformatter/__init__.py
  src/docformatter/__main__.py
  src/docformatter/__pkginfo__.py
  src/docformatter/configuration.py
  src/docformatter/encode.py
  src/docformatter/format.py
  src/docformatter/strings.py
  src/docformatter/syntax.py
  src/docformatter/util.py
  tests/conftest.py
  tests/test_configuration_functions.py
  tests/test_docformatter.py
  tests/test_encoding_functions.py
  tests/test_format_code.py
  tests/test_format_docstring.py
  tests/test_string_functions.py
Labels: chore
