Repository PyCQA/docformatter, pull requests merged in 2023-07, with the labels that each got.

#247 chore: update documentation link for metadata
  pyproject.toml
Labels: chore

#246 test: split format tests into multiple files
  tests/_data/string_files/do_format_code.toml
  tests/_data/string_files/do_format_docstrings.toml
  tests/_data/string_files/format_black.toml
  tests/_data/string_files/format_code.toml
  tests/_data/string_files/format_code_ranges.toml
  tests/_data/string_files/format_epytext.toml
  tests/_data/string_files/format_lists.toml
  tests/_data/string_files/format_sphinx.toml
  tests/_data/string_files/format_style_options.toml
  tests/_data/string_files/format_urls.toml
  tests/_data/string_files/format_wrap.toml
  tests/formatter/__init__.py
  tests/formatter/test_do_format_code.py
  tests/formatter/test_do_format_docstring.py
  tests/formatter/test_format_black.py
  tests/formatter/test_format_code.py
  tests/formatter/test_format_code_ranges.py
  tests/formatter/test_format_epytext.py
  tests/formatter/test_format_lists.py
  tests/formatter/test_format_sphinx.py
  tests/formatter/test_format_styles.py
  tests/formatter/test_format_urls.py
  tests/formatter/test_format_wrap.py
  tests/test_format_code.py
  tests/test_format_docstring.py
  tests/test_strip_docstring.py
Labels: chore

#249 release/v1.7.4
  .github/workflows/on-push-tag.yml
  docs/source/conf.py
  pyproject.toml
  src/docformatter/__pkginfo__.py
  src/docformatter/syntax.py
  tests/_data/string_files/format_sphinx.toml
  tests/formatter/test_format_sphinx.py
Labels: V: patch, release

#254 fix: not recognizing `yield` as a sphinx field name
  src/docformatter/syntax.py
  tests/_data/string_files/format_sphinx.toml
  tests/formatter/test_format_sphinx.py
Labels: P: enhancement, C: style, U: low

#255 release: v1.7.5
  docs/source/conf.py
  pyproject.toml
  src/docformatter/__pkginfo__.py
Labels: V: patch, release

#258 release: v1.7.5
  docs/source/conf.py
  pyproject.toml
  src/docformatter/__pkginfo__.py
Labels: V: patch, release
